### ISSUE TITLE
Enable syntax highlight for AirScript files in VS Code

### ISSUE THREAD

**Issue by bobbinth** [GuildOfWeavers/AirScript#14]
This would require a VS Code extension for syntax highlighting: https://code.visualstudio.com/api/language-extensions/syntax-highlight-guide

**Comment by marinthiercelin** [comment]
Hello,

I started writing a basic syntax highlighter following the guidelines.
It's [here](https://github.com/marinthiercelin/airscript-syntax-highlighter).

I don't have the knowledge on syntax highlighters and vs code extension marketplace to make it a full extension, but it can be a starting point.

**Comment by marinthiercelin** [comment]
I managed to publish the extension on the vs market place: [here](https://marketplace.visualstudio.com/items?itemName=marinthiercelin.airscript-syntax-highlighter)

**Comment by bobbinth** [comment]
Awesome! Thank you so much! Will try to review today.

**Comment by bobbinth** [comment]
This is super cool! I've tried it out on [this example](https://github.com/GuildOfWeavers/AirScript/blob/master/tests/scripts/test.air) and it looks really nice.

How difficult would it be to make the following changes?:

1. Add highlighting for identifiers (variable names). The default VS Code theme uses light-blueish color for these.
2. Use a different color for `yield` and `enforce` keywords. I am thinking these could be colorized similarly to `return` keyword in VS Code (kind of purple color). The `enforce` keyword could be tricky since it can be in different contexts (see lines 76 and 78 in the example).
3. Use a different color for function calls. For example `transition` in `transition($r) on line 78 of the example could be colorized as a function call (kind of yellowish color in default VC Code theme). This also might be tricky as `transition` is used in a different context on line 36.
4. Add highlighting for register references (e.g. `$r`, `$n`) - not really sure what color would work best here.

**Comment by marinthiercelin** [comment]
Hello, I have published a new version that incorporate your suggestions.
Let me know what you think

**Comment by bobbinth** [comment]
Beautiful! I have a few more suggestions. Let me know what you think:

1. Maybe change the `define` keyword coloring to purple (same as `yield` keyword). This would align with how VS Code colors `class` keyword. I'm also thinking that maybe instead of using purple for control flow keywords, we should use it for keywords that define different sections. Specifically, the following keywords would be purple:
  a. `define`
  b. `transition` - in `transition x registers`
  c. `enforce` - in `enforce x constraints`
  d.  `import` - this will be added in the future
  e. Also resolve keywords (`yield` and `enforce`) would also remain purple
2. I'd use the same blue color for `input` keyword as we do for `const` and `static`. These are conceptually the same. I'd keep the color for `secret` and `public` as is. I think it's OK that `secret input` phrase will be of the same color.
3. I'd change the color of `element` and `boolean` keywords to light green (the same color as `prime field` now).
4. I liked how control flow keywords were blue before. What do you think about changing them back? This would include:
  a. `for each`
  b. `init`
  c. `for steps`
  d. `for all steps` - here, would it be possible to have `for` and `steps` blue, but `all` would be of the same color as numbers?
  e. `cycle`
5. With the above changes, I think a better color for register references (`$r` and `$n`) might light green (the same color as `prime field` now).
6. For hexadecimal numbers (lines 83 - 85 in the example), I'd use the same color as for numbers.

Let me know what you think of these - but either way, awesome work!

**Comment by marinthiercelin** [comment]
Hi,
I don't really have a direct control on colors, but I can control the scope of the words, which are translated to colors by your theme. So we might see different colors if we use different schemes.

Anyway, I added all your changes in the last version, let me know if it corresponds to what you had in mind.

**Comment by bobbinth** [comment]
Perfect! I want to make a quick post about this extension on Twitter, and would love to give you a shout out (if you don't mind, of course). Is this you on Twitter: https://twitter.com/MarinThiercelin ?

**Comment by marinthiercelin** [comment]
Yes that's my account.
You can go

**Comment by bobbinth** [comment]
Hi! I've made some updates to AirScript and was wondering if you'd like to update the highlighter as well. Here is a sample file: https://github.com/GuildOfWeavers/AirScript/blob/master/tests/scripts/merkle32.air

The new things are:
1. Multiline comments
2. The `import` statement which includes:
  a. `as` and `from` keywords that should be of the same color as `import` keyword
  b. File path - this should probably be colored in the same was as strings are
3. `with` keywords - this falls into the same category as `for each`, `init` etc.

**Comment by marinthiercelin** [comment]
Hi,
I have added these changes to the last version.

**Comment by bobbinth** [comment]
Thank you! All looks great except for multiline comments `/* ... */`. Are these particularly difficult to do?

**Comment by marinthiercelin** [comment]
My bad I forgot about this.
I just added it to the latest version (0.1.1)

**Comment by bobbinth** [comment]
Awesome! Everything works - thank you!

**Comment by bobbinth** [comment]
I'll close this issue - and if anything else comes up will open a different issue. Thank you again for your help!
